CREATE TABLE instrumentos (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,

    tag VARCHAR(50) NOT NULL UNIQUE,
    descripcion VARCHAR(150) NOT NULL,

    tipo VARCHAR(50) NOT NULL,
    planta VARCHAR(50) NOT NULL,
    area VARCHAR(100) NOT NULL,

    ubicacion_exacta TEXT NOT NULL,
    foto VARCHAR(255) DEFAULT NULL,

    observacion TEXT DEFAULT NULL,

    estado ENUM('activo','inactivo') DEFAULT 'activo',

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
